preload = /home/lainux/Pictures/wallpapers/art/AvYftJY.png
preload = /home/lainux/Pictures/wallpapers/art/B38xXmI.png
preload = /home/lainux/Pictures/wallpapers/animanga/tokyo_ghoul.png

wallpaper = DP-3, /home/lainux/Pictures/wallpapers/animanga/tokyo_ghoul.png
