preload = /home/lainux/Pictures/Wallpapers/Art/AvYftJY.png
preload = /home/lainux/Pictures/Wallpapers/Art/B38xXmI.png
preload = /home/lainux/Pictures/Wallpapers/Animanga/tokyo_ghoul.png

wallpaper = DP-3, /home/lainux/Pictures/wallpapers/animanga/tokyo_ghoul.png
