general {
   lock_cmd = pidof hyprlock || hyprlock
   before_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = 3600 
  on-timeout = pidof hyprlock || hyprlock 
}

listener {
   timeout = 4200
   on-timeout = hyprctl dispatch dms off
   on-resume = hyprctl dispatch dms on 
}
