general {
   hide_cursor = true
   text_trim = false
   ignore_empty_input = true
}

animations {
   enabled = true
   animation = fadeOut, 1, 1.8, linear
}

background {
   monitor =
   path = /home/lainux/Pictures/Wallpapers/Animanga/vagabond-4.png
   blur_passes = 2
}

input-field {
   monitor =
   inner_color = rgba(255, 255, 255, 0.1)
   outer_color = rgb(282828)
   font_color = rgb(504945)
   font_family = JetBrainsMono Nerd Font 
   outline_thickness = 5
   size = 345, 75 
   position = 5, -150
} 

# Main monitor
label {
   monitor = DP-3
   text = $TIME12
   color = rgb(282828)
   font_size = 100
   font_family = JetBrainsMono NF ExtraBold 
   position = 9, 50 
}

label {
   monitor = DP-3
   text = Hello!
   font_family = JetBrainsMono NF ExtraBold
   font_size = 20
   color = rgb(282828)
   position = 9, -80  
}
