# general {
#   lock_cmd = pidof hyprlock || hyprlock
# }

listener {
   timeout = 300
   on-timeout = hyprlock
}

listener {
   timeout = 350
   on-timeout = hyprctl dispatch dpms off
   on-resume = hyprctl dispatch dpms on
}
