general {
   hide_cursor = true
   text_trim = false
}

background {
   monitor =
   path = /home/lainux/Pictures/wallpapers/art/pink_2.jpg 
   blur_passes = 2
}

input-field {
   monitor =
   inner_color = rgba(255, 255, 255, 0.1)
   outer_color = rgba(24273199)
   font_color = rgba(0, 6, 29, 1)
   font_family = FiraCode Nerd Font
   outline_thickness = 5
   size = 345, 75 
   position = -5, -150
} 

label {
   monitor =
   text = $TIME
   color = rgba(213, 153, 167, 1)
   font_size = 100
   font_family = FiraCode Nerd Font Bold
   position = 750, 600
}

# Greeting
label {
   monitor =
   text = Hello, $USER!
   font_family = FiraCode Nerd Font Bold
   font_size = 20
   color = rgba(32, 35, 40, 0.8)
   position = 845, 440  
}
