general {
   hide_cursor = true
}

background {
   monitor =
   path = /home/lainux/Pictures/wallpapers/art/1681785569984228.jpg
}

input-field {
   monitor =
   inner_color = rgba(114, 104, 77, 1)
   outer_color = rgba(17, 17, 17 1.0)
   font_color = rgba(37, 31, 18, 1)
   font_family = FiraCode Nerd Font
   outline_thickness = 6
} 

label {
   monitor =
   text = $TIME12
   color = rgba(111, 106, 86, 1)
   font_size = 100
   position = 630, 800
}
