preload = /home/lainux/Pictures/wallpapers/art/tokyo.webp 
preload = /home/lainux/Pictures/wallpapers/art/morning.png 

wallpaper = DP-3, /home/lainux/Pictures/wallpapers/art/tokyo.webp 
wallpaper = HDMI-A-1, /home/lainux/Pictures/wallpapers/art/tokyo.webp 
