preload = /home/lainux/Pictures/wallpapers/art/Untitled.jpg 

wallpaper = DP-3, /home/lainux/Pictures/wallpapers/art/Untitled.jpg
wallpaper = HDMI-A-1, /home/lainux/Pictures/wallpapers/art/Untitled.jpg 
