general {
   hide_cursor = true
   text_trim = false
}

background {
   monitor =
   path = /home/lainux/Pictures/wallpapers/art/grey_lain_wallpaper.jpg 
   blur_passes = 2
}

input-field {
   monitor =
   inner_color = rgba(255, 255, 255, 0.1)
   outer_color = rgb(272727)
   font_color = rgba(0, 6, 29, 1)
   font_family = FiraCode Nerd Font
   outline_thickness = 5
   size = 345, 75 
   position = -5, -150
} 

# Main monitor
label {
   monitor = DP-3
   text = $TIME
   color = rgb(353432)
   font_size = 100
   font_family = FiraCode Nerd Font Bold
   position = 9, 50 
}

label {
   monitor = DP-3
   text = Hello, $USER!
   font_family = FiraCode Nerd Font Bold
   font_size = 20
   color = rgb(272727)
   position = 9, -80  
}

# Second monitor
#label {
#   monitor = HDMI-A-1  
#   text = $TIME
#   color = rgb(353432) 
#   font_size = 100
#   font_family = FiraCode Nerd Font Bold
#   position = 9, 50 
#}
#
#label {
#   monitor = HDMI-A-1
#   text = Hello, $USER!
#   font_family = FiraCode Nerd Font Bold
#   font_size = 20
#   color = rgb(272727) 
#   position = 9, -80  
#}
