preload = /home/lainux/Pictures/wallpapers/art/a_person_in_a_hat_standing_in_a_room_with_windows.png 
preload = /home/lainux/Pictures/wallpapers/art/grey_lain_wallpaper.jpg 

wallpaper = DP-3, /home/lainux/Pictures/wallpapers/art/a_person_in_a_hat_standing_in_a_room_with_windows.png 
wallpaper = HDMI-A-1, /home/lainux/Pictures/wallpapers/art/grey_lain_wallpaper.jpg 
