[opener]
   open_image = [
      { run = 'feh "$@"', desc = "Open", orphan = true },
]

   edit_text = [
      { run = 'nvim "$@"', block = true, orphan = true },      
]

   read = [
      { run = 'zathura "$@"', desc = "Open", orphan = true },
] 

   play = [
      { run = 'mpv "$@"', orphan = true },
   ]

  open_link = [
      { run = 'librewolf "$@"', orphan = true}
   ]

[open]
prepend_rules = [
   { name = "*.pdf", use = [ "read" ] },
   { name = "*.epub", use = [ "read" ] },
   { name = "*.gif", use = [ "play" ] },
   { name = "*.html", use = [ "open_link" ] },

]
