[opener]
   open_image = [
      { run = 'feh "$@"', desc = "Open", orphan = true },
]

   edit_file = [
      { run = 'nvim "$@"', block = true, orphan = true },      
]

   read-1 = [
      { run = 'zathura "$@"', desc = "Open", orphan = true },
] 

   play = [
      { run = 'mpv "$@"', orphan = true },
   ]

  open_link = [
      { run = 'librewolf "$@"', orphan = true}
   ]

[open]
prepend_rules = [
   { url = "*.pdf", use = [ "read-1" ] },
   { url = "*.epub", use = [ "read-1" ] },
   { url = "*.gif", use = [ "play" ] },
   { url = "*.html", use = [ "open_link" ] },
   { url = "*.toml", use = [ "edit_file" ] }

]
