[opener]
   open = [
      { run = 'feh "$@"', desc = "Open", orphan = true },
]

   edit = [
      { run = 'nvim "$@"', block = true, orphan = true },      
]

   read = [
      { run = 'zathura "$@"', desc = "Open", orphan = true },
] 

   play = [
      { run = 'mpv "$@"', orphan = true },
   ]

[open]
prepend_rules = [
   { name = "*.pdf", use = [ "read" ] },
   { name = "*.epub", use = [ "read" ] },
   { name = "*.gif", use = [ "play" ] },


]
