[opener]
   image_open = [
      { run = 'feh "$@"', orphan = true },
   ]

   file_edit = [
      { run = 'nvim "$@"', block = true, orphan = true },      
   ]

   document_read = [
      { run = 'zathura "$@"', desc = "Open", orphan = true },
   ] 

   video_play = [
      { run = 'mpv "$@"', orphan = true },
   ]

   link_open = [
      { run = 'librewolf "$@"', orphan = true }
   ]
   
   audio_open = [
      { run = 'amberol "$@"', orpan = true }
   ]

[open]
   prepend_rules = [
      # text
      { url = "*.html", use = [ "link_open" ] },
      { url = "*.toml", use = [ "file_edit" ] },
      { url = "*.lua", use = [ "file_edit" ] },
      { url = "*.conf", use = [ "file_edit" ] },
      { url = "*.kdl", use = [ "file_edit" ] },
      { url = "*.ini", use = [ "file_edit" ] },
      { url = "*.json", use = [ "file_edit" ] },
      { url = "*.css", use = [ "file_edit" ] },
      { url = "*.txt", use = [ "file_edit" ] },
      { url = "*.cpp", use = [ "file_edit" ] },

      # images
      { url = "*.png", use = [ "image_open" ] },
      { url = "*.jpeg", use = [ "image_open" ] },
      { url = "*.jpg", use = [ "image_open" ] },
      { url = "*.gif", use = [ "play" ] },
      { url = "*.webp", use = [ "play" ] },
            
      # documents
      { url = "*.pdf", use = [ "document_read" ] },
      { url = "*.epub", use = [ "document_read" ] },
      
      # audio
      { url = "*.mp3", use = [ "audio_open" ] },
   ]
