[opener]
   open_image = [
      { run = 'imv "$@"', orphan = true },
   ]

   edit_file = [
      { run = 'nvim "$@"', block = true, orphan = true },      
   ]

   read-1 = [
      { run = 'zathura "$@"', desc = "Open", orphan = true },
   ] 

   play = [
      { run = 'mpv "$@"', orphan = true },
   ]

   open_link = [
      { run = 'librewolf "$@"', orphan = true}
   ]

[open]
   prepend_rules = [
      # text
      { url = "*.html", use = [ "open_link" ] },
      { url = "*.toml", use = [ "edit_file" ] },
      { url = "*.lua", use = [ "edit_file" ] },
      { url = "*.conf", use = [ "edit_file" ] },
      { url = "*.kdl", use = [ "edit_file" ] },
      { url = "*.ini", use = [ "edit_file" ] },
      { url = "*.json", use = [ "edit_file" ] },
      { url = "*.css", use = [ "edit_file" ] },

      # image
      { url = "*.png", use = [ "open_image" ] },
      { url = "*.jpeg", use = [ "open_image" ] },
      { url = "*.jpg", use = [ "open_image" ] },
      { url = "*.gif", use = [ "play" ] },

      # documents
      { url = "*.pdf", use = [ "read-1" ] },
      { url = "*.epub", use = [ "read-1" ] },
   ]
