# vim:fileencoding=utf-8:foldmethod=marker

# fonts 
  font_family      CaskaydiaCove Nerd Font
  bold_font        auto
  italic_font      auto
  bold_italic_font auto
  font_size 11.0

# cursor
  shell_integration no-cursor
  cursor_shape underline 
  cursor_shape_unfocused hollow
  cursor_trail 10
# cursor_trail_color #EBDBB2

# scrollback
  scrollbar scrolled 
  scrollbar_jump_on_click no

# mouse
  mouse_hide_wait 1.0
# url_color #458588
  detect_urls yes
  show_hyperlink_targets yes 
  underline_hyperlinks always
  paste_actions confirm
  strip_trailing_spaces always
  focus_follows_mouse yes 

# terminal bell
  enable_audio_bell no

# window layout
  enabled_layouts all
# active_border_color #B8BB26 
# inactive_border_color #928374
  window_border_width 1pt
  inactive_text_alpha 0.5

# tab bar
  tab_bar_style powerline 
  tab_powerline_style round 

# color scheme
  background_opacity 1.0 

# advanced
  editor nvim 
  notify_on_cmd_finish unfocused 15 notify

# keyboard shortcuts

# remove all shortcuts definitions up to this point
  clear_all_shortcuts yes

# windows
  map ctrl+enter new_window
  map ctrl+backspace close_window
  map ctrl+] next_window
  map ctrl+[ previous_window
  map ctrl+shift+r start_resizing_window
  map ctrl+alt+w close_os_window

# tabs
  map ctrl+t new_tab
  map ctrl+shift+t new_tab_with_cwd
  map ctrl+shift+w close_tab
  map ctrl+g select_tab
  map ctrl+f detach_tab 
  map ctrl+l next_tab
  map ctrl+h previous_tab
  map ctrl+shift+l move_tab_forward
  map ctrl+shift+h move_tab_backward

# font
  map ctrl+plus change_font_size all +2.0
  map ctrl+minus change_font_size all -2.0
  map ctrl+0 change_font_size all 0

# scrolling
  map ctrl+j scroll_line_down
  map ctrl+k scroll_line_up
  map ctrl+g scroll_home
  map ctrl+shift+g scroll_end

# layout
  map f1 toggle_layout stack
  map f2 toggle_layout tall
  map ctrl+shift+l next_layout 

# clipboard
  map ctrl+c copy_to_clipboard
  map ctrl+v paste_from_clipboard 

# select and act on visible text
  map ctrl+shift+p>f kitten choose-files 
  map ctrl+shift+e open_url_with_hints

# miscellaneous
  map ctrl+shift+f1 show_kitty_doc overview
  map ctrl+shift+u kitten unicode_input

# BEGIN_KITTY_THEME
# Gruvbox Light
include current-theme.conf
# END_KITTY_THEME
